sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tDPJ3PWSY38ZuDeXBWy
    access-key-secret: UQGWh9LhGcibv8RvdH0qAdtEZXXKK1
    bucket-name: sky-dongxuluo
